/* This file is automatically generated from htmltags.in and htmlattrs.in by gennames.py, do not edit */
/* Copyright 2008 Vyacheslav Tokarev */

#import <Foundation/Foundation.h>
#import "htmlConstant.h"

#ifndef HTMLNames_h
#define HTMLNames_h

typedef int OEBControlType;



#define HTMLNamesInstance         ([HTMLNames sharedInstance])

@interface HTMLNames : NSObject

@property (nonatomic, retain) NSDictionary* htmlTagDic;

+ (HTMLNames*) sharedInstance;
- (int) tagWithName:(NSString*)htmlName;
- (NSString*) nameWithTag:(int)tag;

- (BOOL) isTextWithTag:(int)tag;
@end

#endif
