
#import "macros_for_IOS_hk.h"
#import "htmlnames.h"

static HTMLNames* instance = nil;

@implementation HTMLNames

@synthesize htmlTagDic;

+ (HTMLNames*) sharedInstance
{
    @synchronized(self)
    {
        if(instance == nil)
        {
            instance = [[HTMLNames alloc] init];
        }
        return instance;
    }
}

- (int) tagWithName:(NSString*)htmlName
{
    return [[self.htmlTagDic objectForKey:htmlName] intValue];
}

- (NSString*) nameWithTag:(int)tag
{
    NSArray* array = [self.htmlTagDic allKeysForObject:[NSNumber numberWithInt:tag]];
    
    if ([array count])
    {
        return [array objectAtIndex:0];
    }
    else
    {
        return nil;
    }
}

- (BOOL) isTextWithTag:(int)tag
{
    if ((ID_P == tag
         || ID_DIV == tag
         || ID_H1 == tag
         || ID_H2 == tag
         || ID_H3 == tag
         || ID_H4 == tag
         || ID_H5 == tag
         || ID_H6 == tag))
    {
        return YES;
    }
    else {
        return NO;
    }
}

- (BOOL) isInlineTagWithTag:(int)tag
{
    if (ID_A == tag 
    || ID_ABBR == tag  
    || ID_ACRONYM == tag  
    || ID_B == tag  
    || ID_BDO == tag  
    || ID_BIG == tag  
    || ID_BR == tag  
    || ID_CITE == tag  
    || ID_CODE == tag  
    || ID_DFN == tag  
    || ID_EM == tag  
    || ID_I == tag  
    || ID_IMG == tag  
    || ID_INPUT == tag  
    || ID_KBD == tag  
    || ID_LABEL == tag  
    || ID_Q == tag  
    || ID_SAMP == tag  
    || ID_SELECT == tag  
    || ID_SMALL == tag  
    || ID_SPAN == tag  
    || ID_STRONG == tag  
    || ID_SUB == tag  
    || ID_SUP == tag  
    || ID_TEXTAREA == tag 
    || ID_TT == tag 
    || ID_VAR == tag )
        return YES;
    else 
        return NO;
}
- (NSNumber*) localNamePart:(int) number
{
    return [NSNumber numberWithInt:number & NodeImpl_IdLocalMask] ; 
}

- (void) initHtmlTagDic
{
    self.htmlTagDic = [NSDictionary dictionaryWithObjectsAndKeys:
                       [self localNamePart:ID_A], @"a",
                       [self localNamePart:ID_ABBR], @"abbr",
                       [self localNamePart:ID_ACRONYM], @"acronym",
                       [self localNamePart:ID_ADDRESS], @"address",
                       [self localNamePart:ID_APPLET], @"applet",
                       [self localNamePart:ID_AREA], @"area",
                       [self localNamePart:ID_AUDIO], @"audio",
                       [self localNamePart:ID_B], @"b",
                       [self localNamePart:ID_BASE], @"base",
                       [self localNamePart:ID_BASEFONT], @"basefont",
                       [self localNamePart:ID_BDO], @"bdo",
                       [self localNamePart:ID_BIG], @"big",
                       [self localNamePart:ID_BLOCKQUOTE], @"blockquote",
                       [self localNamePart:ID_BODY], @"body",
                       [self localNamePart:ID_BR], @"br",
                       [self localNamePart:ID_BUTTON], @"button",
                       [self localNamePart:ID_CANVAS], @"canvas",
                       [self localNamePart:ID_CAPTION], @"caption",
                       [self localNamePart:ID_CENTER], @"center",
                       [self localNamePart:ID_CITE], @"cite",
                       [self localNamePart:ID_CODE], @"code",
                       [self localNamePart:ID_COL], @"col",
                       [self localNamePart:ID_COLGROUP], @"colgroup",
                       [self localNamePart:ID_DD], @"dd",
                       [self localNamePart:ID_DEL], @"del",
                       [self localNamePart:ID_DFN], @"dfn",
                       [self localNamePart:ID_DIR], @"dir",
                       [self localNamePart:ID_DIV], @"div",
                       [self localNamePart:ID_DL], @"dl",
                       [self localNamePart:ID_DT], @"dt",
                       [self localNamePart:ID_EM], @"em",
                       [self localNamePart:ID_EMBED], @"embed",
                       [self localNamePart:ID_FIELDSET], @"fieldset",
                       [self localNamePart:ID_FONT], @"font",
                       [self localNamePart:ID_FORM], @"form",
                       [self localNamePart:ID_FRAME], @"frame",
                       [self localNamePart:ID_FRAMESET], @"frameset",
                       [self localNamePart:ID_H1], @"h1",
                       [self localNamePart:ID_H2], @"h2",
                       [self localNamePart:ID_H3], @"h3",
                       [self localNamePart:ID_H4], @"h4",
                       [self localNamePart:ID_H5], @"h5",
                       [self localNamePart:ID_H6], @"h6",
                       [self localNamePart:ID_HEAD], @"head",
                       [self localNamePart:ID_HR], @"hr",
                       [self localNamePart:ID_HTML], @"html",
                       [self localNamePart:ID_I], @"i",
                       [self localNamePart:ID_IFRAME], @"iframe",
                       [self localNamePart:ID_ILAYER], @"ilayer",
                       [self localNamePart:ID_IMAGE], @"image",
                       [self localNamePart:ID_IMG], @"img",
                       [self localNamePart:ID_INPUT], @"input",
                       [self localNamePart:ID_INS], @"ins",
                       [self localNamePart:ID_ISINDEX], @"isindex",
                       [self localNamePart:ID_KBD], @"kbd",
                       [self localNamePart:ID_KEYGEN], @"keygen",
                       [self localNamePart:ID_LABEL], @"label",
                       [self localNamePart:ID_LAYER], @"layer",
                       [self localNamePart:ID_LEGEND], @"legend",
                       [self localNamePart:ID_LI], @"li",
                       [self localNamePart:ID_LINK], @"link",
                       [self localNamePart:ID_LISTING], @"listing",
                       [self localNamePart:ID_MAP], @"map",
                       [self localNamePart:ID_MARQUEE], @"marquee",
                       [self localNamePart:ID_MENU], @"menu",
                       [self localNamePart:ID_META], @"meta",
                       [self localNamePart:ID_NOBR], @"nobr",
                       [self localNamePart:ID_NOEMBED], @"noembed",
                       [self localNamePart:ID_NOFRAMES], @"noframes",
                       [self localNamePart:ID_NOSCRIPT], @"noscript",
                       [self localNamePart:ID_NOLAYER], @"nolayer",
                       [self localNamePart:ID_OBJECT], @"object",
                       [self localNamePart:ID_OL], @"ol",
                       [self localNamePart:ID_OPTGROUP], @"optgroup",
                       [self localNamePart:ID_OPTION], @"option",
                       [self localNamePart:ID_P], @"p",
                       [self localNamePart:ID_PARAM], @"param",
                       [self localNamePart:ID_PLAINTEXT], @"plaintext",
                       [self localNamePart:ID_PRE], @"pre",
                       [self localNamePart:ID_Q], @"q",
                       [self localNamePart:ID_S], @"s",
                       [self localNamePart:ID_SAMP], @"samp",
                       [self localNamePart:ID_SCRIPT], @"script",
                       [self localNamePart:ID_SELECT], @"select",
                       [self localNamePart:ID_SMALL], @"small",
                       [self localNamePart:ID_SOURCE], @"source",
                       [self localNamePart:ID_SPAN], @"span",
                       [self localNamePart:ID_STRIKE], @"strike",
                       [self localNamePart:ID_STRONG], @"strong",
                       [self localNamePart:ID_STYLE], @"style",
                       [self localNamePart:ID_SUB], @"sub",
                       [self localNamePart:ID_SUP], @"sup",
                       [self localNamePart:ID_TABLE], @"table",
                       [self localNamePart:ID_TBODY], @"tbody",
                       [self localNamePart:ID_TD], @"td",
                       [self localNamePart:ID_TEXTAREA], @"textarea",
                       [self localNamePart:ID_TFOOT], @"tfoot",
                       [self localNamePart:ID_TH], @"th",
                       [self localNamePart:ID_THEAD], @"thead",
                       [self localNamePart:ID_TITLE], @"title",
                       [self localNamePart:ID_TR], @"tr",
                       [self localNamePart:ID_TT], @"tt",
                       [self localNamePart:ID_U], @"u",
                       [self localNamePart:ID_UL], @"ul",
                       [self localNamePart:ID_VAR], @"var",
                       [self localNamePart:ID_VIDEO], @"video",
                       [self localNamePart:ID_WBR], @"wbr",
                       [self localNamePart:ID_XMP], @"xmp",
                       [self localNamePart:ATTR_ACCEPT_CHARSET], @"accept-charset",
                       [self localNamePart:ATTR_ACCEPT], @"accept",
                       [self localNamePart:ATTR_ACCESSKEY], @"accesskey",
                       [self localNamePart:ATTR_ALIGN], @"align",
                       [self localNamePart:ATTR_ALINK], @"alink",
                       [self localNamePart:ATTR_AUTOCOMPLETE], @"autocomplete",
                       [self localNamePart:ATTR_AUTOPLAY], @"autoplay",
                       [self localNamePart:ATTR_AXIS], @"axis",
                       [self localNamePart:ATTR_BEHAVIOR], @"behavior",
                       [self localNamePart:ATTR_BGCOLOR], @"bgcolor",
                       [self localNamePart:ATTR_BGPROPERTIES], @"bgproperties",
                       [self localNamePart:ATTR_BORDER], @"border",
                       [self localNamePart:ATTR_BORDERCOLOR], @"bordercolor",
                       [self localNamePart:ATTR_CELLPADDING], @"cellpadding",
                       [self localNamePart:ATTR_CELLSPACING], @"cellspacing",
                       [self localNamePart:ATTR_CHAR], @"char",
                       [self localNamePart:ATTR_CHALLENGE], @"challenge",
                       [self localNamePart:ATTR_CHAROFF], @"charoff",
                       [self localNamePart:ATTR_CHARSET], @"charset",
                       [self localNamePart:ATTR_CHECKED], @"checked",
                       [self localNamePart:ATTR_CLEAR], @"clear",
                       [self localNamePart:ATTR_CODETYPE], @"codetype",
                       [self localNamePart:ATTR_COLOR], @"color",
                       [self localNamePart:ATTR_COLS], @"cols",
                       [self localNamePart:ATTR_COLSPAN], @"colspan",
                       [self localNamePart:ATTR_COMPACT], @"compact",
                       [self localNamePart:ATTR_CONTENTEDITABLE], @"contenteditable",
                       [self localNamePart:ATTR_CONTROLS], @"controls",
                       [self localNamePart:ATTR_COORDS], @"coords",
                       [self localNamePart:ATTR_DECLARE], @"declare",
                       [self localNamePart:ATTR_DEFER], @"defer",
                       [self localNamePart:ATTR_DIRECTION], @"direction",
                       [self localNamePart:ATTR_DISABLED], @"disabled",
                       [self localNamePart:ATTR_ENCTYPE], @"enctype",
                       [self localNamePart:ATTR_FACE], @"face",
                       [self localNamePart:ATTR_FRAMEBORDER], @"frameborder",
                       [self localNamePart:ATTR_HEIGHT], @"height",
                       [self localNamePart:ATTR_HIDDEN], @"hidden",
                       [self localNamePart:ATTR_HREFLANG], @"hreflang",
                       [self localNamePart:ATTR_HSPACE], @"hspace",
                       [self localNamePart:ATTR_HTTP_EQUIV], @"http-equiv",
                       [self localNamePart:ATTR_ISMAP], @"ismap",
                       [self localNamePart:ATTR_XML_LANG], @"lang",
                       [self localNamePart:ATTR_LANGUAGE], @"language",
                       [self localNamePart:ATTR_LEFT], @"left",
                       [self localNamePart:ATTR_LEFTMARGIN], @"leftmargin",
                       [self localNamePart:ATTR_LOOP], @"loop",
                       [self localNamePart:ATTR_MARGINHEIGHT], @"marginheight",
                       [self localNamePart:ATTR_MARGINWIDTH], @"marginwidth",
                       [self localNamePart:ATTR_MAXLENGTH], @"maxlength",
                       [self localNamePart:ATTR_MEDIA], @"media",
                       [self localNamePart:ATTR_METHOD], @"method",
                       [self localNamePart:ATTR_MULTIPLE], @"multiple",
                       [self localNamePart:ATTR_NOHREF], @"nohref",
                       [self localNamePart:ATTR_NORESIZE], @"noresize",
                       [self localNamePart:ATTR_NOSAVE], @"nosave",
                       [self localNamePart:ATTR_NOSHADE], @"noshade",
                       [self localNamePart:ATTR_NOWRAP], @"nowrap",
                       [self localNamePart:ATTR_ONABORT], @"onabort",
                       [self localNamePart:ATTR_ONERROR], @"onerror",
                       [self localNamePart:ATTR_ONRESIZE], @"onresize",
                       [self localNamePart:ATTR_OVERSRC], @"oversrc",
                       [self localNamePart:ATTR_PAGEX], @"pagex",
                       [self localNamePart:ATTR_PAGEY], @"pagey",
                       [self localNamePart:ATTR_PLAIN], @"plain",
                       [self localNamePart:ATTR_PLUGINPAGE], @"pluginpage",
                       [self localNamePart:ATTR_PLUGINSPAGE], @"pluginspage",
                       [self localNamePart:ATTR_PLUGINURL], @"pluginurl",
                       [self localNamePart:ATTR_POSTER], @"poster",
                       [self localNamePart:ATTR_READONLY], @"readonly",
                       [self localNamePart:ATTR_REL], @"rel",
                       [self localNamePart:ATTR_REV], @"rev",
                       [self localNamePart:ATTR_ROWS], @"rows",
                       [self localNamePart:ATTR_ROWSPAN], @"rowspan",
                       [self localNamePart:ATTR_RULES], @"rules",
                       [self localNamePart:ATTR_SCOPE], @"scope",
                       [self localNamePart:ATTR_SCROLLAMOUNT], @"scrollamount",
                       [self localNamePart:ATTR_SCROLLDELAY], @"scrolldelay",
                       [self localNamePart:ATTR_SCROLLING], @"scrolling",
                       [self localNamePart:ATTR_SELECTED], @"selected",
                       [self localNamePart:ATTR_SHAPE], @"shape",
                       [self localNamePart:ATTR_SIZE], @"size",
                       [self localNamePart:ATTR_START], @"start",
                       [self localNamePart:ATTR_TABINDEX], @"tabindex",
                       [self localNamePart:ATTR_TARGET], @"target",
                       [self localNamePart:ATTR_TEXT], @"text",
                       [self localNamePart:ATTR_TOP], @"top",
                       [self localNamePart:ATTR_TOPMARGIN], @"topmargin",
                       [self localNamePart:ATTR_TRUESPEED], @"truespeed",
                       [self localNamePart:ATTR_XLINK_TYPE], @"type",
                       [self localNamePart:ATTR_UNKNOWN], @"unknown",
                       [self localNamePart:ATTR_VALIGN], @"valign",
                       [self localNamePart:ATTR_VALUETYPE], @"valuetype",
                       [self localNamePart:ATTR_VERSION], @"version",
                       [self localNamePart:ATTR_VISIBILITY], @"visibility",
                       [self localNamePart:ATTR_VLINK], @"vlink",
                       [self localNamePart:ATTR_VSPACE], @"vspace",
                       [self localNamePart:ATTR_WIDTH], @"width",
                       [self localNamePart:ATTR_WRAP], @"wrap",
                       [self localNamePart:ATTR_Z_INDEX], @"z-index",
                       [self localNamePart:ATTR_ACTION], @"action",
                       [self localNamePart:ATTR_ALT], @"alt",
                       [self localNamePart:ATTR_ARCHIVE], @"archive",
                       [self localNamePart:ATTR_BACKGROUND], @"background",
                       [self localNamePart:ATTR_CLASS], @"class",
                       [self localNamePart:ATTR_CLASSID], @"classid",
                       [self localNamePart:ATTR_CODEBASE], @"codebase",
                       [self localNamePart:ATTR_CONTENT], @"content",
                       [self localNamePart:ATTR_DATA], @"data",
                       [self localNamePart:ATTR_DATETIME], @"datetime",
                       [self localNamePart:ATTR_FOR], @"for",
                       [self localNamePart:ATTR_HEADERS], @"headers",
                       [self localNamePart:ATTR_XLINK_HREF], @"href",
                       [self localNamePart:ATTR_ID], @"id",
                       [self localNamePart:ATTR_LONGDESC], @"longdesc",
                       [self localNamePart:ATTR_NAME], @"name",
                       [self localNamePart:ATTR_ONBLUR], @"onblur",
                       [self localNamePart:ATTR_ONCHANGE], @"onchange",
                       [self localNamePart:ATTR_ONCLICK], @"onclick",
                       [self localNamePart:ATTR_ONDBLCLICK], @"ondblclick",
                       [self localNamePart:ATTR_ONFOCUS], @"onfocus",
                       [self localNamePart:ATTR_ONKEYDOWN], @"onkeydown",
                       [self localNamePart:ATTR_ONKEYPRESS], @"onkeypress",
                       [self localNamePart:ATTR_ONKEYUP], @"onkeyup",
                       [self localNamePart:ATTR_ONLOAD], @"onload",
                       [self localNamePart:ATTR_ONMOUSEDOWN], @"onmousedown",
                       [self localNamePart:ATTR_ONMOUSEMOVE], @"onmousemove",
                       [self localNamePart:ATTR_ONMOUSEOUT], @"onmouseout",
                       [self localNamePart:ATTR_ONMOUSEOVER], @"onmouseover",
                       [self localNamePart:ATTR_ONMOUSEUP], @"onmouseup",
                       [self localNamePart:ATTR_ONRESET], @"onreset",
                       [self localNamePart:ATTR_ONSELECT], @"onselect",
                       [self localNamePart:ATTR_ONSCROLL], @"onscroll",
                       [self localNamePart:ATTR_ONSUBMIT], @"onsubmit",
                       [self localNamePart:ATTR_ONUNLOAD], @"onunload",
                       [self localNamePart:ATTR_PROFILE], @"profile",
                       [self localNamePart:ATTR_PROMPT], @"prompt",
                       [self localNamePart:ATTR_SCHEME], @"scheme",
                       [self localNamePart:ATTR_SRC], @"src",
                       [self localNamePart:ATTR_STANDBY], @"standby",
                       [self localNamePart:ATTR_SUMMARY], @"summary",
                       [self localNamePart:ATTR_USEMAP], @"usemap",
                       [self localNamePart:ATTR_VALUE], @"value",
                       [self localNamePart:ID_ALTGLYPH], @"altGlyph",
                       [self localNamePart:ID_ALTGLYPHDEF], @"altGlyphDef",
                       [self localNamePart:ID_ALTGLYPHITEM], @"altGlyphItem",
                       [self localNamePart:ID_ANIMATE], @"animate",
                       [self localNamePart:ID_ANIMATECOLOR], @"animateColor",
                       [self localNamePart:ID_ANIMATEMOTION], @"animateMotion",
                       [self localNamePart:ID_ANIMATETRANSFORM], @"animateTransform",
                       [self localNamePart:ID_SET], @"set",
                       [self localNamePart:ID_CIRCLE], @"circle",
                       [self localNamePart:ID_CLIPPATH], @"clipPath",
                       [self localNamePart:ID_COLOR_PROFILE], @"color_profile",
                       [self localNamePart:ID_CURSOR], @"cursor",
                       [self localNamePart:ID_DEFINITION_SRC], @"definition_src",
                       [self localNamePart:ID_DEFS], @"defs",
                       [self localNamePart:ID_DESC], @"desc",
                       [self localNamePart:ID_ELLIPSE], @"ellipse",
                       [self localNamePart:ID_FEBLEND], @"feBlend",
                       [self localNamePart:ID_FECOLORMATRIX], @"feColorMatrix",
                       [self localNamePart:ID_FECOMPONENTTRANSFER], @"feComponentTransfer",
                       [self localNamePart:ID_FECOMPOSITE], @"feComposite",
                       [self localNamePart:ID_FECONVOLVEMATRIX], @"feConvolveMatrix",
                       [self localNamePart:ID_FEDIFFUSELIGHTING], @"feDiffuseLighting",
                       [self localNamePart:ID_FEDISPLACEMENTMAP], @"feDisplacementMap",
                       [self localNamePart:ID_FEDISTANTLIGHT], @"feDistantLight",
                       [self localNamePart:ID_FEFLOOD], @"feFlood",
                       [self localNamePart:ID_FEFUNCA], @"feFuncA",
                       [self localNamePart:ID_FEFUNCB], @"feFuncB",
                       [self localNamePart:ID_FEFUNCG], @"feFuncG",
                       [self localNamePart:ID_FEFUNCR], @"feFuncR",
                       [self localNamePart:ID_FEGAUSSIANBLUR], @"feGaussianBlur",
                       [self localNamePart:ID_FEIMAGE], @"feImage",
                       [self localNamePart:ID_FEMERGE], @"feMerge",
                       [self localNamePart:ID_FEMERGENODE], @"feMergeNode",
                       [self localNamePart:ID_FEMORPHOLOGY], @"feMorphology",
                       [self localNamePart:ID_FEOFFSET], @"feOffset",
                       [self localNamePart:ID_FEPOINTLIGHT], @"fePointLight",
                       [self localNamePart:ID_FESPECULARLIGHTING], @"feSpecularLighting",
                       [self localNamePart:ID_FESPOTLIGHT], @"feSpotLight",
                       [self localNamePart:ID_FETILE], @"feTile",
                       [self localNamePart:ID_FETURBULENCE], @"feTurbulence",
                       [self localNamePart:ID_FILTER], @"filter",
                       [self localNamePart:ID_FONT_FACE], @"font_face",
                       [self localNamePart:ID_FONT_FACE_FORMAT], @"font_face_format",
                       [self localNamePart:ID_FONT_FACE_NAME], @"font_face_name",
                       [self localNamePart:ID_FONT_FACE_SRC], @"font_face_src",
                       [self localNamePart:ID_FONT_FACE_URI], @"font_face_uri",
                       [self localNamePart:ID_FOREIGNOBJECT], @"foreignObject",
                       [self localNamePart:ID_G], @"g",
                       [self localNamePart:ID_GLYPH], @"glyph",
                       [self localNamePart:ID_GLYPHREF], @"glyphRef",
                       [self localNamePart:ID_HKERN], @"hkern",
                       [self localNamePart:ID_LINE], @"line",
                       [self localNamePart:ID_LINEARGRADIENT], @"linearGradient",
                       [self localNamePart:ID_MARKER], @"marker",
                       [self localNamePart:ID_MASK], @"mask",
                       [self localNamePart:ID_METADATA], @"metadata",
                       [self localNamePart:ID_MISSING_GLYPH], @"missing_glyph",
                       [self localNamePart:ID_MPATH], @"mpath",
                       [self localNamePart:ID_PATH], @"path",
                       [self localNamePart:ID_PATTERN], @"pattern",
                       [self localNamePart:ID_POLYGON], @"polygon",
                       [self localNamePart:ID_POLYLINE], @"polyline",
                       [self localNamePart:ID_RADIALGRADIENT], @"radialGradient",
                       [self localNamePart:ID_RECT], @"rect",
                       [self localNamePart:ID_STOP], @"stop",
                       [self localNamePart:ID_SVG], @"svg",
                       [self localNamePart:ID_SWITCH], @"switch",
                       [self localNamePart:ID_SYMBOL], @"symbol",
                       [self localNamePart:ID_TEXTPATH], @"textPath",
                       [self localNamePart:ID_TREF], @"tref",
                       [self localNamePart:ID_TSPAN], @"tspan",
                       [self localNamePart:ID_USE], @"use",
                       [self localNamePart:ID_VIEW], @"view",
                       [self localNamePart:ID_VKERN], @"vkern",
                       [self localNamePart:ATTR_ACCENT_HEIGHT], @"accent-height",
                       [self localNamePart:ATTR_ACCUMULATE], @"accumulate",
                       [self localNamePart:ATTR_ADDITIVE], @"additive",
                       [self localNamePart:ATTR_ALIGNMENT_BASELINE], @"alignment-baseline",
                       [self localNamePart:ATTR_ALPHABETIC], @"alphabetic",
                       [self localNamePart:ATTR_AMPLITUDE], @"amplitude",
                       [self localNamePart:ATTR_ARABIC_FORM], @"arabic-form",
                       [self localNamePart:ATTR_ASCENT], @"ascent",
                       [self localNamePart:ATTR_ATTRIBUTENAME], @"attributeName",
                       [self localNamePart:ATTR_ATTRIBUTETYPE], @"attributeType",
                       [self localNamePart:ATTR_AZIMUTH], @"azimuth",
                       [self localNamePart:ATTR_BASEFREQUENCY], @"baseFrequency",
                       [self localNamePart:ATTR_BASELINE_SHIFT], @"baseline-shift",
                       [self localNamePart:ATTR_BASEPROFILE], @"baseProfile",
                       [self localNamePart:ATTR_BBOX], @"bbox",
                       [self localNamePart:ATTR_BEGIN], @"begin",
                       [self localNamePart:ATTR_BIAS], @"bias",
                       [self localNamePart:ATTR_BY], @"by",
                       [self localNamePart:ATTR_CALCMODE], @"calcMode",
                       [self localNamePart:ATTR_CAP_HEIGHT], @"cap-height",
                       [self localNamePart:ATTR_CLIP], @"clip",
                       [self localNamePart:ATTR_CLIP_PATH], @"clip-path",
                       [self localNamePart:ATTR_CLIP_RULE], @"clip-rule",
                       [self localNamePart:ATTR_CLIPPATHUNITS], @"clipPathUnits",
                       [self localNamePart:ATTR_COLOR_INTERPOLATION], @"color-interpolation",
                       [self localNamePart:ATTR_COLOR_INTERPOLATION_FILTERS], @"color-interpolation-filters",
                       [self localNamePart:ATTR_COLOR_PROFILE], @"color-profile",
                       [self localNamePart:ATTR_COLOR_RENDERING], @"color-rendering",
                       [self localNamePart:ATTR_CONTENTSCRIPTTYPE], @"contentScriptType",
                       [self localNamePart:ATTR_CONTENTSTYLETYPE], @"contentStyleType",
                       [self localNamePart:ATTR_CX], @"cx",
                       [self localNamePart:ATTR_CY], @"cy",
                       [self localNamePart:ATTR_D], @"d",
                       [self localNamePart:ATTR_DESCENT], @"descent",
                       [self localNamePart:ATTR_DIFFUSECONSTANT], @"diffuseConstant",
                       [self localNamePart:ATTR_DISPLAY], @"display",
                       [self localNamePart:ATTR_DIVISOR], @"divisor",
                       [self localNamePart:ATTR_DOMINANT_BASELINE], @"dominant-baseline",
                       [self localNamePart:ATTR_DUR], @"dur",
                       [self localNamePart:ATTR_DX], @"dx",
                       [self localNamePart:ATTR_DY], @"dy",
                       [self localNamePart:ATTR_EDGEMODE], @"edgeMode",
                       [self localNamePart:ATTR_ELEVATION], @"elevation",
                       [self localNamePart:ATTR_ENABLE_BACKGROUND], @"enable-background",
                       [self localNamePart:ATTR_END], @"end",
                       [self localNamePart:ATTR_EXPONENT], @"exponent",
                       [self localNamePart:ATTR_EXTERNALRESOURCESREQUIRED], @"externalResourcesRequired",
                       [self localNamePart:ATTR_FILL], @"fill",
                       [self localNamePart:ATTR_FILL_OPACITY], @"fill-opacity",
                       [self localNamePart:ATTR_FILL_RULE], @"fill-rule",
                       [self localNamePart:ATTR_FILTERRES], @"filterRes",
                       [self localNamePart:ATTR_FILTERUNITS], @"filterUnits",
                       [self localNamePart:ATTR_FLOOD_COLOR], @"flood-color",
                       [self localNamePart:ATTR_FLOOD_OPACITY], @"flood-opacity",
                       [self localNamePart:ATTR_FONT_FAMILY], @"font-family",
                       [self localNamePart:ATTR_FONT_SIZE], @"font-size",
                       [self localNamePart:ATTR_FONT_SIZE_ADJUST], @"font-size-adjust",
                       [self localNamePart:ATTR_FONT_STRETCH], @"font-stretch",
                       [self localNamePart:ATTR_FONT_STYLE], @"font-style",
                       [self localNamePart:ATTR_FONT_VARIANT], @"font-variant",
                       [self localNamePart:ATTR_FONT_WEIGHT], @"font-weight",
                       [self localNamePart:ATTR_FORMAT], @"format",
                       [self localNamePart:ATTR_FROM], @"from",
                       [self localNamePart:ATTR_FX], @"fx",
                       [self localNamePart:ATTR_FY], @"fy",
                       [self localNamePart:ATTR_G1], @"g1",
                       [self localNamePart:ATTR_G2], @"g2",
                       [self localNamePart:ATTR_GLYPH_NAME], @"glyph-name",
                       [self localNamePart:ATTR_GLYPH_ORIENTATION_HORIZONTAL], @"glyph-orientation-horizontal",
                       [self localNamePart:ATTR_GLYPH_ORIENTATION_VERTICAL], @"glyph-orientation-vertical",
                       [self localNamePart:ATTR_GRADIENTTRANSFORM], @"gradientTransform",
                       [self localNamePart:ATTR_GRADIENTUNITS], @"gradientUnits",
                       [self localNamePart:ATTR_HANGING], @"hanging",
                       [self localNamePart:ATTR_HORIZ_ADV_X], @"horiz-adv-x",
                       [self localNamePart:ATTR_HORIZ_ORIGIN_X], @"horiz-origin-x",
                       [self localNamePart:ATTR_HORIZ_ORIGIN_Y], @"horiz-origin-y",
                       [self localNamePart:ATTR_IDEOGRAPHIC], @"ideographic",
                       [self localNamePart:ATTR_IMAGE_RENDERING], @"image-rendering",
                       [self localNamePart:ATTR_IN], @"in",
                       [self localNamePart:ATTR_IN2], @"in2",
                       [self localNamePart:ATTR_INTERCEPT], @"intercept",
                       [self localNamePart:ATTR_K], @"k",
                       [self localNamePart:ATTR_K1], @"k1",
                       [self localNamePart:ATTR_K2], @"k2",
                       [self localNamePart:ATTR_K3], @"k3",
                       [self localNamePart:ATTR_K4], @"k4",
                       [self localNamePart:ATTR_KERNELMATRIX], @"kernelMatrix",
                       [self localNamePart:ATTR_KERNELUNITLENGTH], @"kernelUnitLength",
                       [self localNamePart:ATTR_KERNING], @"kerning",
                       [self localNamePart:ATTR_KEYPOINTS], @"keyPoints",
                       [self localNamePart:ATTR_KEYSPLINES], @"keySplines",
                       [self localNamePart:ATTR_KEYTIMES], @"keyTimes",
                       [self localNamePart:ATTR_LENGTHADJUST], @"lengthAdjust",
                       [self localNamePart:ATTR_LETTER_SPACING], @"letter-spacing",
                       [self localNamePart:ATTR_LIGHTING_COLOR], @"lighting-color",
                       [self localNamePart:ATTR_LIMITINGCONEANGLE], @"limitingConeAngle",
                       [self localNamePart:ATTR_LOCAL], @"local",
                       [self localNamePart:ATTR_MARKER_END], @"marker-end",
                       [self localNamePart:ATTR_MARKER_MID], @"marker-mid",
                       [self localNamePart:ATTR_MARKER_START], @"marker-start",
                       [self localNamePart:ATTR_MARKERHEIGHT], @"markerHeight",
                       [self localNamePart:ATTR_MARKERUNITS], @"markerUnits",
                       [self localNamePart:ATTR_MARKERWIDTH], @"markerWidth",
                       [self localNamePart:ATTR_MASKCONTENTUNITS], @"maskContentUnits",
                       [self localNamePart:ATTR_MASKUNITS], @"maskUnits",
                       [self localNamePart:ATTR_MATHEMATICAL], @"mathematical",
                       [self localNamePart:ATTR_MAX], @"max",
                       [self localNamePart:ATTR_MIN], @"min",
                       [self localNamePart:ATTR_MODE], @"mode",
                       [self localNamePart:ATTR_NUMOCTAVES], @"numOctaves",
                       [self localNamePart:ATTR_OFFSET], @"offset",
                       [self localNamePart:ATTR_ONACTIVATE], @"onactivate",
                       [self localNamePart:ATTR_ONBEGIN], @"onbegin",
                       [self localNamePart:ATTR_ONEND], @"onend",
                       [self localNamePart:ATTR_ONFOCUSIN], @"onfocusin",
                       [self localNamePart:ATTR_ONFOCUSOUT], @"onfocusout",
                       [self localNamePart:ATTR_ONREPEAT], @"onrepeat",
                       [self localNamePart:ATTR_ONZOOM], @"onzoom",
                       [self localNamePart:ATTR_OPACITY], @"opacity",
                       [self localNamePart:ATTR_OPERATOR], @"operator",
                       [self localNamePart:ATTR_ORDER], @"order",
                       [self localNamePart:ATTR_ORIENT], @"orient",
                       [self localNamePart:ATTR_ORIENTATION], @"orientation",
                       [self localNamePart:ATTR_ORIGIN], @"origin",
                       [self localNamePart:ATTR_OVERFLOW], @"overflow",
                       [self localNamePart:ATTR_OVERLINE_POSITION], @"overline-position",
                       [self localNamePart:ATTR_OVERLINE_THICKNESS], @"overline-thickness",
                       [self localNamePart:ATTR_PANOSE_1], @"panose-1",
                       [self localNamePart:ATTR_PATHLENGTH], @"pathLength",
                       [self localNamePart:ATTR_PATTERNCONTENTUNITS], @"patternContentUnits",
                       [self localNamePart:ATTR_PATTERNTRANSFORM], @"patternTransform",
                       [self localNamePart:ATTR_PATTERNUNITS], @"patternUnits",
                       [self localNamePart:ATTR_POINTER_EVENTS], @"pointer-events",
                       [self localNamePart:ATTR_POINTS], @"points",
                       [self localNamePart:ATTR_POINTSATX], @"pointsAtX",
                       [self localNamePart:ATTR_POINTSATY], @"pointsAtY",
                       [self localNamePart:ATTR_POINTSATZ], @"pointsAtZ",
                       [self localNamePart:ATTR_PRESERVEALPHA], @"preserveAlpha",
                       [self localNamePart:ATTR_PRESERVEASPECTRATIO], @"preserveAspectRatio",
                       [self localNamePart:ATTR_PRIMITIVEUNITS], @"primitiveUnits",
                       [self localNamePart:ATTR_R], @"r",
                       [self localNamePart:ATTR_RADIUS], @"radius",
                       [self localNamePart:ATTR_REFX], @"refX",
                       [self localNamePart:ATTR_REFY], @"refY",
                       [self localNamePart:ATTR_RENDERING_INTENT], @"rendering-intent",
                       [self localNamePart:ATTR_REPEATCOUNT], @"repeatCount",
                       [self localNamePart:ATTR_REPEATDUR], @"repeatDur",
                       [self localNamePart:ATTR_REQUIREDEXTENSIONS], @"requiredExtensions",
                       [self localNamePart:ATTR_REQUIREDFEATURES], @"requiredFeatures",
                       [self localNamePart:ATTR_RESTART], @"restart",
                       [self localNamePart:ATTR_RESULT], @"result",
                       [self localNamePart:ATTR_ROTATE], @"rotate",
                       [self localNamePart:ATTR_RX], @"rx",
                       [self localNamePart:ATTR_RY], @"ry",
                       [self localNamePart:ATTR_SCALE], @"scale",
                       [self localNamePart:ATTR_SEED], @"seed",
                       [self localNamePart:ATTR_SHAPE_RENDERING], @"shape-rendering",
                       [self localNamePart:ATTR_SLOPE], @"slope",
                       [self localNamePart:ATTR_SPACING], @"spacing",
                       [self localNamePart:ATTR_SPECULARCONSTANT], @"specularConstant",
                       [self localNamePart:ATTR_SPECULAREXPONENT], @"specularExponent",
                       [self localNamePart:ATTR_SPREADMETHOD], @"spreadMethod",
                       [self localNamePart:ATTR_STARTOFFSET], @"startOffset",
                       [self localNamePart:ATTR_STDDEVIATION], @"stdDeviation",
                       [self localNamePart:ATTR_STEMH], @"stemh",
                       [self localNamePart:ATTR_STEMV], @"stemv",
                       [self localNamePart:ATTR_STITCHTILES], @"stitchTiles",
                       [self localNamePart:ATTR_STOP_COLOR], @"stop-color",
                       [self localNamePart:ATTR_STOP_OPACITY], @"stop-opacity",
                       [self localNamePart:ATTR_STRIKETHROUGH_POSITION], @"strikethrough-position",
                       [self localNamePart:ATTR_STRIKETHROUGH_THICKNESS], @"strikethrough-thickness",
                       [self localNamePart:ATTR_STROKE], @"stroke",
                       [self localNamePart:ATTR_STROKE_DASHARRAY], @"stroke-dasharray",
                       [self localNamePart:ATTR_STROKE_DASHOFFSET], @"stroke-dashoffset",
                       [self localNamePart:ATTR_STROKE_LINECAP], @"stroke-linecap",
                       [self localNamePart:ATTR_STROKE_LINEJOIN], @"stroke-linejoin",
                       [self localNamePart:ATTR_STROKE_MITERLIMIT], @"stroke-miterlimit",
                       [self localNamePart:ATTR_STROKE_OPACITY], @"stroke-opacity",
                       [self localNamePart:ATTR_STROKE_WIDTH], @"stroke-width",
                       [self localNamePart:ATTR_SURFACESCALE], @"surfaceScale",
                       [self localNamePart:ATTR_SYSTEMLANGUAGE], @"systemLanguage",
                       [self localNamePart:ATTR_TABLEVALUES], @"tableValues",
                       [self localNamePart:ATTR_TARGETX], @"targetX",
                       [self localNamePart:ATTR_TARGETY], @"targetY",
                       [self localNamePart:ATTR_TEXT_ANCHOR], @"text-anchor",
                       [self localNamePart:ATTR_TEXT_DECORATION], @"text-decoration",
                       [self localNamePart:ATTR_TEXT_RENDERING], @"text-rendering",
                       [self localNamePart:ATTR_TEXTLENGTH], @"textLength",
                       [self localNamePart:ATTR_TO], @"to",
                       [self localNamePart:ATTR_TRANSFORM], @"transform",
                       [self localNamePart:ATTR_U1], @"u1",
                       [self localNamePart:ATTR_U2], @"u2",
                       [self localNamePart:ATTR_UNDERLINE_POSITION], @"underline-position",
                       [self localNamePart:ATTR_UNDERLINE_THICKNESS], @"underline-thickness",
                       [self localNamePart:ATTR_UNICODE], @"unicode",
                       [self localNamePart:ATTR_UNICODE_BIDI], @"unicode-bidi",
                       [self localNamePart:ATTR_UNICODE_RANGE], @"unicode-range",
                       [self localNamePart:ATTR_UNITS_PER_EM], @"units-per-em",
                       [self localNamePart:ATTR_V_ALPHABETIC], @"v-alphabetic",
                       [self localNamePart:ATTR_V_HANGING], @"v-hanging",
                       [self localNamePart:ATTR_V_IDEOGRAPHIC], @"v-ideographic",
                       [self localNamePart:ATTR_V_MATHEMATICAL], @"v-mathematical",
                       [self localNamePart:ATTR_VALUES], @"values",
                       [self localNamePart:ATTR_VERT_ADV_Y], @"vert-adv-y",
                       [self localNamePart:ATTR_VERT_ORIGIN_X], @"vert-origin-x",
                       [self localNamePart:ATTR_VERT_ORIGIN_Y], @"vert-origin-y",
                       [self localNamePart:ATTR_VIEWBOX], @"viewBox",
                       [self localNamePart:ATTR_VIEWTARGET], @"viewTarget",
                       [self localNamePart:ATTR_WIDTHS], @"widths",
                       [self localNamePart:ATTR_WORD_SPACING], @"word-spacing",
                       [self localNamePart:ATTR_WRITING_MODE], @"writing-mode",
                       [self localNamePart:ATTR_X], @"x",
                       [self localNamePart:ATTR_X_HEIGHT], @"x-height",
                       [self localNamePart:ATTR_X1], @"x1",
                       [self localNamePart:ATTR_X2], @"x2",
                       [self localNamePart:ATTR_XCHANNELSELECTOR], @"xChannelSelector",
                       [self localNamePart:ATTR_Y], @"y",
                       [self localNamePart:ATTR_Y1], @"y1",
                       [self localNamePart:ATTR_Y2], @"y2",
                       [self localNamePart:ATTR_YCHANNELSELECTOR], @"yChannelSelector",
                       [self localNamePart:ATTR_Z], @"z",
                       [self localNamePart:ATTR_ZOOMANDPAN], @"zoomAndPan",
                       [self localNamePart:ATTR_XLINK_ACTUATE], @"actuate",
                       [self localNamePart:ATTR_XLINK_ARCROLE], @"arcrole",
                       [self localNamePart:ATTR_XLINK_ROLE], @"role",
                       [self localNamePart:ATTR_XLINK_SHOW], @"show",
                       [self localNamePart:ATTR_XML_SPACE], @"space",
                       nil];
}

- (id) init
{
    START_TIMER
    if (self = [super init])
    {   
        if (!self.htmlTagDic)
        {
            [self initHtmlTagDic];
        }
    }
    END_TIMER(@"htmlNameinit")
    return self;
}

- (void) dealloc
{
    self.htmlTagDic = nil;
    [super dealloc];
}
@end